version: '3.8'

services:
    dev:
        container_name: nestjs_api_dev
        image: nestjs-api-dev:1.0.0
        # depends_on:
        #     - db
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:dev
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    prod:
        container_name: nestjs_api_prod
        image: nestjs-api-prod:1.0.0
        # depends_on:
        #     - db
        build:
            context: .
            target: production
            dockerfile: ./Dockerfile
        command: npm run start:prod
        ports:
            - 3000:3000
            - 9229:9229
        networks:
            - nesjs-network
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
    # db:
    #     image: mongo
    #     container_name: db_mongo
    #     ports:
    #         - "2701:27017"
    #     networks:
    #         - nesjs-network
    #     healthcheck:
    #         test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    #         interval: 30s
    #         timeout: 10s
    #         retries: 3
    #     restart: unless-stopped

networks:
    nesjs-network: